Repository AY2425S1-CS2103T-F13-2/tp, pull requests merged in 2024-11, with the labels that each got.

#183 Update parser mode switching
  src/main/java/seedu/address/logic/parser/AbcliParser.java
Labels: type.Task, priority.High

#185 Update Logic section of Developer Guide
  docs/DeveloperGuide.md
  docs/diagrams/ParserClasses.puml
  docs/images/ParserClasses.png
Labels: type.Task, priority.High

#191 Update UG and DG
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/images/MeetUpClash.png
  docs/images/PropertyView.png
Labels: type.Enhancement, priority.High

#192 Fix Bugs and JavaDocs
  docs/UserGuide.md
  src/main/java/seedu/address/logic/commands/meetup/AddCommand.java
  src/main/java/seedu/address/logic/commands/meetup/EditCommand.java
  src/main/java/seedu/address/logic/commands/meetup/FindCommand.java
  src/main/java/seedu/address/logic/commands/property/DeleteCommand.java
  src/main/java/seedu/address/logic/commands/property/FindCommand.java
  src/main/java/seedu/address/logic/commands/property/ViewCommand.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/meetup/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/meetup/EditCommandParser.java
  src/main/java/seedu/address/logic/parser/meetup/FindCommandParser.java
  src/main/java/seedu/address/model/meetup/Subject.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/ModelStub.java
  src/test/java/seedu/address/logic/commands/buyer/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/meetup/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/meetup/FindCommandTest.java
  src/test/java/seedu/address/logic/commands/property/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/property/DeleteCommandTest.java
  src/test/java/seedu/address/logic/commands/property/FindCommandTest.java
  src/test/java/seedu/address/logic/parser/meetup/AddCommandParserTest.java
  src/test/java/seedu/address/logic/parser/meetup/EditCommandParserTest.java
  src/test/java/seedu/address/logic/parser/meetup/FindCommandParserTest.java
  src/test/java/seedu/address/logic/parser/meetup/MeetUpCommandParserTest.java
  src/test/java/seedu/address/logic/parser/property/FindCommandParserTest.java
  src/test/java/seedu/address/model/meetup/MeetUpTest.java
  src/test/java/seedu/address/testutil/meetup/MeetUpUtil.java
  src/test/java/seedu/address/testutil/meetup/TypicalMeetUps.java
Labels: type.Bug, priority.High

#186 Update DG and UML
  docs/DeveloperGuide.md
  docs/diagrams/ArchitectureSequenceDiagram.puml
  docs/diagrams/StorageClassDiagram.puml
  docs/images/ArchitectureSequenceDiagram.png
  docs/images/StorageClassDiagram.png
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/storage/Storage.java
  src/main/java/seedu/address/storage/StorageManager.java
  src/main/java/seedu/address/storage/property/PropertyListStorage.java
  src/test/java/seedu/address/storage/StorageManagerTest.java
Labels: type.Task, priority.High

#194 Update dg implementation
  docs/DeveloperGuide.md
  docs/diagrams/DeleteMeetUpActivityDiagram.puml
  docs/images/DeleteMeetUpActivityDiagram.png
Labels: type.Task, priority.High

#197 Update Quick Start Ui and new switch information
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/images/SwitchMeetUpAfter.png
  docs/images/SwitchMeetUpBefore.png
  docs/images/Ui.png
Labels: type.Task, priority.High

#204 Add logging and assertions
  src/main/java/seedu/address/commons/exceptions/DataLoadingException.java
  src/main/java/seedu/address/logic/commands/buyer/AddCommand.java
  src/main/java/seedu/address/logic/commands/buyer/DeleteCommand.java
  src/main/java/seedu/address/logic/commands/buyer/EditCommand.java
  src/main/java/seedu/address/logic/commands/exceptions/CommandException.java
  src/main/java/seedu/address/logic/commands/meetup/AddCommand.java
  src/main/java/seedu/address/logic/commands/meetup/DeleteCommand.java
  src/main/java/seedu/address/logic/commands/meetup/EditCommand.java
  src/main/java/seedu/address/logic/commands/meetup/ViewCommand.java
  src/main/java/seedu/address/logic/commands/property/AddCommand.java
  src/main/java/seedu/address/logic/commands/property/DeleteCommand.java
  src/main/java/seedu/address/logic/commands/property/EditCommand.java
  src/main/java/seedu/address/logic/parser/exceptions/ParseException.java
  src/main/java/seedu/address/model/BuyerList.java
  src/main/java/seedu/address/model/MeetUpList.java
  src/main/java/seedu/address/model/PropertyList.java
  src/main/java/seedu/address/model/buyer/exceptions/BuyerNotFoundException.java
  src/main/java/seedu/address/model/buyer/exceptions/DuplicateBuyerException.java
  src/main/java/seedu/address/model/meetup/exceptions/DuplicateMeetUpException.java
  src/main/java/seedu/address/model/meetup/exceptions/MeetUpNotFoundException.java
  src/main/java/seedu/address/model/property/exceptions/DuplicatePropertyException.java
  src/main/java/seedu/address/model/property/exceptions/PropertyNotFoundException.java
  src/main/java/seedu/address/ui/meetup/MeetUpListPanel.java
Labels: type.Enhancement, priority.Low

#208 Update Buyer portion in UG
  docs/UserGuide.md
  docs/images/BuyerModeDisplay.png
  docs/images/findAlexDavidResult.png
Labels: type.Task, priority.High

#209 Fix alpha-test bug in buyer
  src/main/java/seedu/address/model/tag/Tag.java
  src/main/java/seedu/address/model/util/SampleBuyerDataUtil.java
Labels: priority.Low, severity.Low, alpha-bug

#213 update command summary and user stories
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/ModelClassDiagram.puml
  docs/images/ModelClassDiagram.png
Labels: type.Task, priority.High

#216 Update UG FAQ and added default images for the different modes
  docs/UserGuide.md
  docs/images/BuyerModeInitialList.png
  docs/images/MeetUpModeInitialList.png
  docs/images/PropertyModeInitialList.png
Labels: type.Task, priority.High

#214 Fix AddedBuyer Bug
  src/main/java/seedu/address/logic/Logic.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/meetup/AddedBuyer.java
  src/main/java/seedu/address/storage/meetup/JsonAdaptedAddedBuyer.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/meetup/MeetUpCard.java
  src/main/java/seedu/address/ui/meetup/MeetUpListPanel.java
  src/test/java/seedu/address/logic/commands/ModelStub.java
  src/test/java/seedu/address/model/meetup/AddedBuyerTest.java
  src/test/java/seedu/address/testutil/meetup/MeetUpUtil.java
Labels: priority.High, severity.Low, alpha-bug

#220 Update UI UML diagram
  docs/diagrams/UiClassDiagram.puml
  docs/images/UiClassDiagram.png
Labels: type.Enhancement, priority.High

#218 Update UG, DG and UML diagram
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/StorageClassDiagram.puml
  docs/images/PropertyModeDisplay.png
  docs/images/SwitchPropertyAfter.png
  docs/images/SwitchPropertyBefore.png
Labels: type.Enhancement, type.Task, priority.Medium

#225 Correct minor errors and formatting issues in UG
  docs/UserGuide.md
  docs/images/BuyerModeInitialList.png
  docs/images/FindBuyerSequence.png
  docs/images/FindMeetUpSequence.png
  docs/images/FindPropertySequence.png
  docs/images/MeetUpModeInitialList.png
  docs/images/PropertyModeInitialList.png
  docs/images/SwitchBuyerToMeetUpSequence.png
Labels: type.Task, priority.High

#243 Fix assigned alpha bugs
  src/main/java/seedu/address/logic/commands/buyer/ClearCommand.java
  src/main/java/seedu/address/logic/commands/meetup/ClearCommand.java
  src/main/java/seedu/address/logic/commands/property/ClearCommand.java
  src/main/java/seedu/address/logic/parser/buyer/BuyerCommandParser.java
  src/main/java/seedu/address/logic/parser/meetup/MeetUpCommandParser.java
  src/main/java/seedu/address/logic/parser/property/PropertyCommandParser.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/StatusBarFooter.java
  src/test/java/seedu/address/logic/commands/buyer/ClearCommandTest.java
  src/test/java/seedu/address/logic/commands/buyer/EditCommandTest.java
  src/test/java/seedu/address/logic/commands/meetup/ClearCommandTest.java
  src/test/java/seedu/address/logic/commands/meetup/EditCommandTest.java
  src/test/java/seedu/address/logic/commands/property/ClearCommandTest.java
  src/test/java/seedu/address/logic/commands/property/EditCommandTest.java
Labels: type.Bug, priority.High

#249 Update switch to show data list even if it was filtered beforehand
  src/main/java/seedu/address/logic/commands/SwitchParserModeCommand.java
  src/test/java/seedu/address/logic/commands/SwitchParserModeCommandTest.java
Labels: type.Task, priority.High, severity.Medium, alpha-bug

#244 Branch fix logger alpha bug
  src/main/java/seedu/address/MainApp.java
  src/main/java/seedu/address/commons/core/LogsCenter.java
  src/main/java/seedu/address/model/BuyerList.java
  src/main/java/seedu/address/model/MeetUpList.java
  src/main/java/seedu/address/model/PropertyList.java
  src/main/java/seedu/address/storage/buyer/JsonBuyerListStorage.java
  src/main/resources/view/MainWindow.fxml
Labels: type.Task, priority.Low, severity.Low, alpha-bug

#246 Fix alpha bug with help link
  src/main/java/seedu/address/ui/HelpWindow.java
Labels: type.Task, priority.Low, severity.Low, alpha-bug

#247 Fix date range overlap bug
  src/main/java/seedu/address/ui/meetup/MeetUpListPanel.java
Labels: type.Task, priority.Medium, severity.Low, alpha-bug

#248 Fix date time error msg
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/meetup/DateTime.java
  src/main/java/seedu/address/model/meetup/From.java
  src/main/java/seedu/address/model/meetup/To.java
  src/main/java/seedu/address/storage/meetup/JsonAdaptedMeetUp.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/parser/meetup/AddCommandParserTest.java
  src/test/java/seedu/address/logic/parser/meetup/EditCommandParserTest.java
  src/test/java/seedu/address/model/meetup/DateTimeTest.java
  src/test/java/seedu/address/model/meetup/FromTest.java
  src/test/java/seedu/address/model/meetup/ToTest.java
  src/test/java/seedu/address/storage/meetup/JsonAdaptedMeetUpTest.java
Labels: type.Task, priority.Low, severity.Low, alpha-bug

#250 Correct property type section typo of successful command message
  src/main/java/seedu/address/logic/Messages.java
Labels: type.Task, priority.Medium, severity.Low, alpha-bug

#255 Correct errors in User Guide
  docs/UserGuide.md
  docs/images/PropertyModeInitialList.png
Labels: type.Task, priority.Medium, severity.Medium, alpha-bug

#256 Fix bugs
  docs/images/PropertyModeInitialList.png
  src/main/java/seedu/address/logic/commands/buyer/AddCommand.java
  src/main/java/seedu/address/logic/commands/buyer/FindCommand.java
  src/main/java/seedu/address/logic/commands/meetup/EditCommand.java
  src/main/java/seedu/address/logic/commands/meetup/FindCommand.java
  src/main/java/seedu/address/logic/commands/property/FindCommand.java
  src/main/java/seedu/address/model/util/SamplePropertyDataUtil.java
Labels: type.Bug, priority.Medium, severity.Medium, alpha-bug

#253 Fix meetup to from
  src/main/java/seedu/address/logic/commands/meetup/AddCommand.java
  src/main/java/seedu/address/logic/commands/meetup/EditCommand.java
  src/main/java/seedu/address/model/meetup/MeetUp.java
  src/main/java/seedu/address/model/meetup/To.java
  src/main/java/seedu/address/storage/meetup/JsonAdaptedMeetUp.java
  src/test/java/seedu/address/logic/commands/meetup/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/meetup/EditCommandTest.java
  src/test/java/seedu/address/model/meetup/MeetUpTest.java
  src/test/java/seedu/address/model/meetup/ToTest.java
  src/test/java/seedu/address/storage/meetup/JsonAdaptedMeetUpTest.java
Labels: type.Bug, priority.High, severity.High, alpha-bug

#257 Update UG images
  docs/images/BuyerModeInitialList.png
  docs/images/FindBuyerSequence.png
  docs/images/FindMeetUpSequence.png
  docs/images/FindPropertySequence.png
  docs/images/MeetUpModeInitialList.png
  docs/images/PropertyModeInitialList.png
  docs/images/SwitchBuyerToMeetUpSequence.png
  docs/images/Ui.png
  docs/images/helpMessage.png
Labels: type.Task, priority.High

#259 Change version number in MainApp
  src/main/java/seedu/address/MainApp.java
Labels: type.Task, severity.VeryLow

#329 Refactor error message for invalid To-From relationship
  src/main/java/seedu/address/logic/commands/meetup/AddCommand.java
  src/main/java/seedu/address/logic/commands/meetup/EditCommand.java
Labels: type.Bug, priority.High, severity.Medium

#260 Correct duplicate requirements for add meetup in UG
  docs/UserGuide.md
Labels: type.Task, priority.High

#332 Fix bugs from PE-D
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/images/StorageClassDiagram.png
  src/main/java/seedu/address/logic/commands/meetup/EditCommand.java
  src/main/java/seedu/address/logic/commands/property/FindCommand.java
  src/main/java/seedu/address/logic/parser/meetup/EditCommandParser.java
Labels: type.Task, priority.Medium, severity.Medium

#328 Fix assigned UG bugs from PE-Dry
  docs/DeveloperGuide.md
  docs/UserGuide.md
Labels: type.Task, priority.High

#335 Fix ug bugs
  docs/UserGuide.md
  docs/images/MeetUpModeInitialList.png
  docs/images/PropertyModeInitialList.png
Labels: type.Task, priority.High

#333 Fix and add more manual test in DG
  docs/DeveloperGuide.md
  docs/UserGuide.md
  src/main/java/seedu/address/logic/Messages.java
Labels: type.Task, priority.High

#334 Fix MSS in DG
  docs/DeveloperGuide.md
Labels: type.Task, priority.High

#336 Add how to use user guide and improve quick start in UG
  docs/UserGuide.md
Labels: type.Task, priority.High

#337 Improve readability for clients
  docs/UserGuide.md
  docs/images/GuiGuide.png
  docs/images/MacGuide.png
  docs/images/WindowsGuide.png
Labels: type.Task, priority.High

#331 Fix assigned PE bugs
  docs/DeveloperGuide.md
  docs/UserGuide.md
  src/main/java/seedu/address/logic/commands/meetup/AddCommand.java
Labels: type.Bug, priority.High, alpha-bug

#330 Update UG
  docs/UserGuide.md
Labels: type.Task, priority.High, severity.Medium

#338 Add FAQ and fix UG bugs
  docs/UserGuide.md
Labels: type.Task, priority.High

#340 Add a glossary of terms for unclear terms
  docs/UserGuide.md
Labels: type.Enhancement, priority.Medium, severity.Low

#339 Correct UG minor bugs, update colours, and format pages
  docs/UserGuide.md
Labels: type.Task, priority.High

#342 Update DG to reflect planned enhancement for long overflow
  docs/DeveloperGuide.md
Labels: type.Task, priority.High

#345 Add closing tags for table rows
  docs/UserGuide.md
Labels: type.Task, priority.High

#346 Fix bug and add missing details
  docs/UserGuide.md
Labels: type.Task, priority.High

#343 Fix DG appendix and add tips
  docs/DeveloperGuide.md
  docs/UserGuide.md
Labels: type.Task, priority.High

#347 Branch ug final
  docs/UserGuide.md
  src/main/java/seedu/address/model/buyer/Email.java
Labels: type.Task, priority.High

#348 Correct formatting
  docs/DeveloperGuide.md
  docs/diagrams/ModelClassDiagram.puml
  docs/diagrams/StorageClassDiagram.puml
  docs/images/StorageClassDiagram.png
Labels: type.Task, priority.High

#349 Fix developer guide
  docs/DeveloperGuide.md
  docs/diagrams/BuyerMeetUpModelClassDiagram.puml
  docs/diagrams/ModelClassDiagram.puml
  docs/diagrams/PropertyModelClassDiagram.puml
  docs/images/BetterModelClassDiagram.png
  docs/images/BuyerMeetUpModelClassDiagram.png
  docs/images/BuyerModelClassDiagram.png
  docs/images/ModelClassDiagram.png
  docs/images/PropertyModelClassDiagram.png
Labels: type.Task, priority.High

#350 Fix bugs in DG
  docs/DeveloperGuide.md
  docs/images/BuyerMeetUpModelClassDiagram.png
Labels: type.Task, priority.High

#351 Fix UG and DG bugs
  docs/DeveloperGuide.md
  docs/UserGuide.md
Labels: type.Task, priority.High

#352 fix UG and DG bugs
  docs/DeveloperGuide.md
Labels: type.Task, priority.High

#353 Fix bugs
  docs/DeveloperGuide.md
  docs/diagrams/ModelClassDiagram.puml
  docs/images/ModelClassDiagram.png
Labels: type.Task, priority.High
