Repository AY2425S1-CS2103T-F13-2/tp, pull requests merged in 2024-10, with the labels that each got.

#35 Update target user profile in Developer Guide
  docs/DeveloperGuide.md
Labels: type.Task

#37 Update user stories in Developer Guide
  docs/DeveloperGuide.md
Labels: type.Task, priority.High

#39 Update README
  README.md
Labels: type.Task, priority.High

#40 Update homepage
  docs/index.md
Labels: type.Task, priority.High

#41 Update settings
  docs/_config.yml
  docs/_sass/minima/_base.scss
Labels: type.Task, priority.High

#42 Add expected updates userguide
  docs/UserGuide.md
Labels: type.Task, priority.High

#43 Update user guide context to match ABCLI
  docs/UserGuide.md
Labels: type.Task, priority.High

#46 Add Non-Functional Requirements
  docs/DeveloperGuide.md
Labels: type.Task, priority.High

#50 Add Glossary
  docs/DeveloperGuide.md
Labels: type.Task, priority.High

#49 Edit use cases for DeveloperGuide.md
  docs/DeveloperGuide.md
Labels: type.Task, priority.High

#51 Add ui mockup
  docs/images/Ui.png
Labels: type.Task, priority.High

#57 Add client type
  docs/UserGuide.md
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/person/PersonType.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/PersonListCard.fxml
  src/test/data/JsonAddressBookStorageTest/invalidAndValidPersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/duplicatePersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/address/model/person/PersonTest.java
  src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
  src/test/java/seedu/address/testutil/PersonUtil.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: type.Story, priority.High

#59 Add Schedule and MeetUp class skeleton
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/meetup/MeetUp.java
  src/main/java/seedu/address/model/schedule/Schedule.java
Labels: type.Story, priority.High

#65 Add meetup toString
  src/main/java/seedu/address/model/meetup/MeetUp.java
Labels: type.Story, priority.High

#72 Add meetup class
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/commands/AddMeetUpCommand.java
  src/main/java/seedu/address/logic/parser/AddMeetUpCommandParser.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/model/meetup/MeetUp.java
Labels: type.Task, priority.High

#63 Enable filtering by person type in view
  src/main/java/seedu/address/logic/commands/ViewCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/ViewCommandParser.java
  src/main/java/seedu/address/model/person/PersonFulfilsPredicate.java
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/ViewCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
Labels: type.Task, priority.High

#69 Add skeleton for view meetup
  src/main/java/seedu/address/logic/commands/FilterMeetUpCommand.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/meetup/MeetUpContainsDate.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/FilterMeetUpCommandTest.java
Labels: type.Story, priority.High

#78 Add more comments to MeetUp class
  src/main/java/seedu/address/model/meetup/MeetUp.java
Labels: type.Task, priority.High

#88 Create test cases for personType
  src/main/java/seedu/address/logic/commands/EditPersonCommand.java
  src/main/java/seedu/address/logic/parser/EditPersonCommandParser.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/EditPersonDescriptorTest.java
  src/test/java/seedu/address/logic/parser/AddPersonCommandParserTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/EditPersonCommandParserTest.java
  src/test/java/seedu/address/testutil/EditPersonDescriptorBuilder.java
  src/test/java/seedu/address/testutil/PersonUtil.java
Labels: type.Task, priority.High

#89 Integration of testcase with model
  src/main/java/seedu/address/MainApp.java
  src/main/java/seedu/address/logic/commands/EditMeetUpCommand.java
  src/main/java/seedu/address/logic/parser/AddMeetUpCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/meetup/From.java
  src/main/java/seedu/address/model/meetup/Info.java
  src/main/java/seedu/address/model/meetup/MeetUp.java
  src/main/java/seedu/address/model/meetup/Name.java
  src/main/java/seedu/address/model/meetup/To.java
  src/main/java/seedu/address/model/util/SampleMeetUpDataUtil.java
  src/main/java/seedu/address/model/util/SampleMeetUpList.java
  src/main/java/seedu/address/model/util/SamplePersonDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedMeetUp.java
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/AddPersonCommandIntegrationTest.java
  src/test/java/seedu/address/logic/commands/AddPersonCommandTest.java
  src/test/java/seedu/address/logic/commands/ClearCommandTest.java
  src/test/java/seedu/address/logic/commands/DeletePersonCommandTest.java
  src/test/java/seedu/address/logic/commands/EditPersonCommandTest.java
  src/test/java/seedu/address/logic/commands/FindPersonCommandTest.java
  src/test/java/seedu/address/logic/commands/ViewPersonCommandTest.java
  src/test/java/seedu/address/model/ModelManagerTest.java
  src/test/java/seedu/address/storage/StorageManagerTest.java
  src/test/java/seedu/address/testutil/MeetUpBuilder.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
  src/test/java/seedu/address/testutil/TypicalMeetUps.java
Labels: type.Bug, priority.High

#93 Finish UI for meetup
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/commands/FilterMeetUpCommand.java
  src/main/java/seedu/address/logic/commands/ViewMeetUpCommand.java
  src/main/java/seedu/address/storage/JsonAdaptedMeetUp.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/MeetUpCard.java
  src/main/java/seedu/address/ui/MeetUpListPanel.java
  src/main/resources/view/MainWindow.fxml
Labels: type.Enhancement, priority.High

#92 Add test cases for ViewMeetupCommand
  src/main/java/seedu/address/logic/commands/CommandResult.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/ViewMeetupCommandTest.java
Labels: type.Task, priority.High

#98 Add meetup command test cases
  src/main/java/seedu/address/logic/commands/AddMeetUpCommand.java
  src/test/java/seedu/address/logic/commands/AddMeetUpCommandIntegrationTest.java
  src/test/java/seedu/address/logic/commands/AddMeetUpCommandTest.java
Labels: type.Task, priority.High

#99 Add storage test cases
  src/main/java/seedu/address/model/meetup/Info.java
  src/main/java/seedu/address/model/meetup/Name.java
  src/main/java/seedu/address/storage/JsonAdaptedMeetUp.java
  src/main/java/seedu/address/storage/JsonSerializableMeetUpList.java
  src/test/data/JsonMeetUpListStorageTest/invalidAndValidMeetUpList.json
  src/test/data/JsonMeetUpListStorageTest/invalidMeetUpList.json
  src/test/data/JsonMeetUpListStorageTest/notJsonFormatMeetUpList.json
  src/test/data/JsonSerializableMeetUpListTest/duplicateMeetUpMeetUpList.json
  src/test/data/JsonSerializableMeetUpListTest/invalidMeetUpList.json
  src/test/data/JsonSerializableMeetUpListTest/typicalMeetUpsMeetUpList.json
  src/test/java/seedu/address/storage/JsonAdaptedMeetUpTest.java
  src/test/java/seedu/address/storage/JsonMeetUpListStorageTest.java
  src/test/java/seedu/address/storage/JsonSerializableMeetUpListTest.java
Labels: type.Task, priority.High

#95 Add working edit and delete tests
  src/main/java/seedu/address/logic/commands/EditMeetUpCommand.java
  src/main/java/seedu/address/logic/commands/FilterMeetUpCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/model/meetup/From.java
  src/main/java/seedu/address/model/meetup/MeetUpContainsDate.java
  src/main/java/seedu/address/model/meetup/MeetUpContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/meetup/To.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/DeleteMeetUpCommandTest.java
  src/test/java/seedu/address/logic/commands/EditMeetUpCommandTest.java
  src/test/java/seedu/address/testutil/EditMeetUpDescriptorBuilder.java
  src/test/java/seedu/address/testutil/TypicalIndexes.java
Labels: type.Task, priority.High

#103 Fix delete meetup method
  src/main/java/seedu/address/model/ModelManager.java
Labels: type.Task, priority.High

#100 Write testcases for model and fix bugs
  src/main/java/seedu/address/logic/commands/AddMeetUpCommand.java
  src/main/java/seedu/address/logic/commands/CommandResult.java
  src/main/java/seedu/address/logic/commands/DeleteMeetUpCommand.java
  src/main/java/seedu/address/logic/commands/EditMeetUpCommand.java
  src/main/java/seedu/address/logic/commands/FilterMeetUpCommand.java
  src/main/java/seedu/address/logic/commands/ViewMeetUpCommand.java
  src/main/java/seedu/address/logic/parser/AddMeetUpCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/meetup/From.java
  src/main/java/seedu/address/model/meetup/Info.java
  src/main/java/seedu/address/model/meetup/MeetUp.java
  src/main/java/seedu/address/model/meetup/To.java
  src/main/java/seedu/address/model/meetup/UniqueMeetUpList.java
  src/main/java/seedu/address/model/meetup/exceptions/MeetUpNotFoundException.java
  src/main/java/seedu/address/model/schedule/Schedule.java
  src/main/java/seedu/address/storage/JsonAdaptedMeetUp.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/DeleteMeetUpCommandTest.java
  src/test/java/seedu/address/logic/commands/EditMeetUpCommandTest.java
  src/test/java/seedu/address/logic/commands/ViewMeetupCommandTest.java
  src/test/java/seedu/address/model/MeetUpListTest.java
  src/test/java/seedu/address/model/ModelManagerTest.java
  src/test/java/seedu/address/model/meetup/FromTest.java
  src/test/java/seedu/address/model/meetup/InfoTest.java
  src/test/java/seedu/address/model/meetup/MeetUpTest.java
  src/test/java/seedu/address/model/meetup/NameTest.java
  src/test/java/seedu/address/model/meetup/ToTest.java
  src/test/java/seedu/address/model/meetup/UniqueMeetUpListTest.java
  src/test/java/seedu/address/storage/JsonAdaptedMeetUpTest.java
  src/test/java/seedu/address/storage/JsonMeetUpListStorageTest.java
  src/test/java/seedu/address/testutil/MeetUpListBuilder.java
  src/test/java/seedu/address/testutil/TypicalMeetUps.java
Labels: type.Bug, priority.High

#105 Edit view meet up syntax
  build.gradle
  src/main/java/seedu/address/logic/commands/ViewMeetUpCommand.java
Labels: type.Task, priority.Medium

#113 Add Storage for Property
  src/main/java/seedu/address/storage/property/JsonAdaptedProperty.java
  src/main/java/seedu/address/storage/property/JsonPropertyListStorage.java
  src/main/java/seedu/address/storage/property/JsonSerializablePropertyList.java
  src/main/java/seedu/address/storage/property/PropertyListStorage.java
Labels: type.Enhancement, priority.High

#115 Add meet up timing highlighting
  src/main/java/seedu/address/model/MeetUpList.java
  src/main/java/seedu/address/storage/StorageManager.java
  src/main/java/seedu/address/ui/MeetUpCard.java
  src/main/java/seedu/address/ui/MeetUpListPanel.java
Labels: type.Enhancement, priority.High

#116 Add property model
  src/main/java/seedu/address/model/property/AskingPrice.java
  src/main/java/seedu/address/model/property/LandlordName.java
  src/main/java/seedu/address/model/property/Location.java
  src/main/java/seedu/address/model/property/Phone.java
  src/main/java/seedu/address/model/property/Property.java
  src/main/java/seedu/address/model/property/PropertyType.java
  src/main/java/seedu/address/model/property/UniquePropertyList.java
  src/main/java/seedu/address/model/property/exceptions/DuplicatePropertyException.java
  src/main/java/seedu/address/model/property/exceptions/PropertyNotFoundException.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/model/property/AskingPriceTest.java
  src/test/java/seedu/address/model/property/LandlordNameTest.java
  src/test/java/seedu/address/model/property/LocationTest.java
  src/test/java/seedu/address/model/property/PhoneTest.java
  src/test/java/seedu/address/model/property/PropertyTest.java
  src/test/java/seedu/address/model/property/PropertyTypeTest.java
  src/test/java/seedu/address/testutil/PropertyBuilder.java
  src/test/java/seedu/address/testutil/TypicalProperties.java
Labels: type.Task, priority.High

#119 Closes #117
  src/main/java/seedu/address/model/PropertyList.java
  src/main/java/seedu/address/model/ReadOnlyPropertyList.java
  src/main/java/seedu/address/model/property/UniquePropertyList.java
Labels: type.Task, priority.High

#118 Finish find command for meet ups
  src/main/java/seedu/address/logic/commands/meetup/FindCommand.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/parser/meetup/AddCommandParserTest.java
  src/test/java/seedu/address/logic/parser/meetup/DeleteCommandParserTest.java
  src/test/java/seedu/address/logic/parser/meetup/EditCommandParserTest.java
  src/test/java/seedu/address/logic/parser/meetup/FilterCommandParserTest.java
  src/test/java/seedu/address/logic/parser/meetup/FindCommandParserTest.java
Labels: type.Task, priority.High

#124 Closes #121
  src/main/java/seedu/address/MainApp.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/PropertyList.java
  src/main/java/seedu/address/model/ReadOnlyUserPrefs.java
  src/main/java/seedu/address/model/UserPrefs.java
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/ClearCommandTest.java
  src/test/java/seedu/address/logic/commands/buyer/AddCommandIntegrationTest.java
  src/test/java/seedu/address/logic/commands/buyer/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/buyer/DeleteCommandTest.java
  src/test/java/seedu/address/logic/commands/buyer/EditCommandTest.java
  src/test/java/seedu/address/logic/commands/buyer/FindCommandTest.java
  src/test/java/seedu/address/logic/commands/buyer/ViewCommandTest.java
  src/test/java/seedu/address/logic/commands/meetup/AddCommandIntegrationTest.java
  src/test/java/seedu/address/logic/commands/meetup/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/meetup/DeleteCommandTest.java
  src/test/java/seedu/address/logic/commands/meetup/EditCommandTest.java
  src/test/java/seedu/address/logic/commands/meetup/ViewCommandTest.java
  src/test/java/seedu/address/model/ModelManagerTest.java
  src/test/java/seedu/address/model/property/PropertyTest.java
  src/test/java/seedu/address/testutil/property/PropertyBuilder.java
  src/test/java/seedu/address/testutil/property/TypicalProperties.java
Labels: type.Task, priority.High

#125 Add budget and remove unnecessary fields in Buyer class
  docs/DevOps.md
  docs/DeveloperGuide.md
  docs/SettingUp.md
  docs/Testing.md
  docs/UserGuide.md
  docs/diagrams/BetterModelClassDiagram.puml
  docs/diagrams/ModelClassDiagram.puml
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/commands/ClearCommand.java
  src/main/java/seedu/address/logic/commands/CommandResult.java
  src/main/java/seedu/address/logic/commands/ExitCommand.java
  src/main/java/seedu/address/logic/commands/buyer/AddCommand.java
  src/main/java/seedu/address/logic/commands/buyer/EditCommand.java
  src/main/java/seedu/address/logic/commands/buyer/ViewCommand.java
  src/main/java/seedu/address/logic/parser/BuyerListParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/logic/parser/buyer/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/buyer/EditCommandParser.java
  src/main/java/seedu/address/logic/parser/buyer/ViewCommandParser.java
  src/main/java/seedu/address/model/buyer/Address.java
  src/main/java/seedu/address/model/buyer/Budget.java
  src/main/java/seedu/address/model/buyer/Buyer.java
  src/main/java/seedu/address/model/buyer/BuyerFulfilsPredicate.java
  src/main/java/seedu/address/model/buyer/BuyerType.java
  src/main/java/seedu/address/model/util/SampleBuyerDataUtil.java
  src/main/java/seedu/address/storage/buyer/JsonAdaptedBuyer.java
  src/main/java/seedu/address/storage/buyer/JsonSerializableBuyerList.java
  src/main/java/seedu/address/ui/BuyerCard.java
  src/main/resources/view/BuyerListCard.fxml
  src/main/resources/view/DarkTheme.css
  src/test/data/JsonBuyerListStorageTest/invalidAndValidBuyerBuyerList.json
  src/test/data/JsonBuyerListStorageTest/invalidBuyerBuyerList.json
  src/test/data/JsonSerializableBuyerListTest/duplicateBuyerBuyerList.json
  src/test/data/JsonSerializableBuyerListTest/invalidBuyerBuyerList.json
  src/test/data/JsonSerializableBuyerListTest/typicalBuyersBuyerList.json
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/buyer/EditBuyerDescriptorTest.java
  src/test/java/seedu/address/logic/commands/buyer/ViewCommandTest.java
  src/test/java/seedu/address/logic/parser/BuyerListParserTest.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/logic/parser/buyer/AddCommandParserTest.java
  src/test/java/seedu/address/logic/parser/buyer/EditCommandParserTest.java
  src/test/java/seedu/address/logic/parser/buyer/ViewCommandParserTest.java
  src/test/java/seedu/address/model/BuyerListTest.java
  src/test/java/seedu/address/model/buyer/AddressTest.java
  src/test/java/seedu/address/model/buyer/BudgetTest.java
  src/test/java/seedu/address/model/buyer/BuyerFulfilsPredicateTest.java
  src/test/java/seedu/address/model/buyer/BuyerTest.java
  src/test/java/seedu/address/model/buyer/NameContainsKeywordsPredicateTest.java
  src/test/java/seedu/address/model/buyer/UniqueBuyerListTest.java
  src/test/java/seedu/address/storage/JsonAdaptedBuyerTest.java
  src/test/java/seedu/address/testutil/buyer/BuyerBuilder.java
  src/test/java/seedu/address/testutil/buyer/BuyerListBuilder.java
  src/test/java/seedu/address/testutil/buyer/BuyerUtil.java
  src/test/java/seedu/address/testutil/buyer/EditBuyerDescriptorBuilder.java
  src/test/java/seedu/address/testutil/buyer/TypicalBuyers.java
  src/test/resources/view/UiPartTest/validFileWithFxRoot.fxml
Labels: type.Story, priority.High

#127 Close issue #120
  src/test/java/seedu/address/logic/parser/meetup/AddCommandParserTest.java
  src/test/java/seedu/address/logic/parser/meetup/DeleteCommandParserTest.java
Labels: type.Task, priority.High

#131 3 mode parser
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/commands/CommandResult.java
  src/main/java/seedu/address/logic/commands/SwitchParserModeCommand.java
  src/main/java/seedu/address/logic/commands/meetup/AddCommand.java
  src/main/java/seedu/address/logic/commands/meetup/DeleteCommand.java
  src/main/java/seedu/address/logic/commands/meetup/EditCommand.java
  src/main/java/seedu/address/logic/commands/meetup/ViewCommand.java
  src/main/java/seedu/address/logic/commands/property/ViewCommand.java
  src/main/java/seedu/address/logic/parser/AbcliParser.java
  src/main/java/seedu/address/logic/parser/BuyerListParser.java
  src/main/java/seedu/address/logic/parser/CommandParser.java
  src/main/java/seedu/address/logic/parser/ParserMode.java
  src/main/java/seedu/address/logic/parser/SwitchParserModeCommandParser.java
  src/main/java/seedu/address/logic/parser/buyer/BuyerCommandParser.java
  src/main/java/seedu/address/logic/parser/meetup/MeetUpCommandParser.java
  src/main/java/seedu/address/logic/parser/property/PropertyCommandParser.java
  src/test/java/seedu/address/logic/commands/CommandResultTest.java
  src/test/java/seedu/address/logic/parser/BuyerListParserTest.java
Labels: type.Task, priority.High

#136 Close issue #133
  docs/UserGuide.md
  src/main/java/seedu/address/logic/commands/meetup/FindCommand.java
Labels: type.Task, priority.High

#137 UserGuide Prototype
  docs/UserGuide.md
Labels: type.Task, priority.Low

#140 Close issue #139
  src/main/java/seedu/address/logic/commands/meetup/FindCommand.java
  src/main/java/seedu/address/logic/parser/meetup/FindCommandParser.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/parser/meetup/FindCommandParserTest.java
  src/test/java/seedu/address/logic/parser/meetup/MeetUpCommandParserTest.java
Labels: type.Task, priority.High

#142 Closes #141
  docs/UserGuide.md
Labels: type.Task, priority.High

#146 Update version number in MainApp
  build.gradle
  src/main/java/seedu/address/MainApp.java
Labels: type.Task, priority.High

#150 Edit some UML diagrams for Logic
  docs/DeveloperGuide.md
  docs/diagrams/DeleteSequenceDiagram.puml
  docs/diagrams/LogicClassDiagram.puml
  docs/diagrams/ParserClasses.puml
  docs/images/DeleteSequenceDiagram.png
  docs/images/LogicClassDiagram.png
  docs/images/ParserClasses.png
Labels: type.Task, priority.High

#157 Add property UML
  docs/diagrams/PropertyClassDiagram.puml
Labels: type.Enhancement, priority.High

#151 Improve UI
  src/main/java/seedu/address/logic/commands/buyer/AddCommand.java
  src/main/java/seedu/address/logic/commands/meetup/AddCommand.java
  src/main/java/seedu/address/logic/commands/meetup/EditCommand.java
  src/main/java/seedu/address/model/buyer/Budget.java
  src/main/java/seedu/address/model/meetup/From.java
  src/main/java/seedu/address/model/meetup/To.java
  src/main/java/seedu/address/model/property/AskingPrice.java
  src/main/java/seedu/address/storage/property/JsonAdaptedProperty.java
  src/main/java/seedu/address/ui/buyer/BuyerCard.java
  src/main/java/seedu/address/ui/meetup/MeetUpCard.java
  src/main/java/seedu/address/ui/property/PropertyCard.java
  src/main/resources/view/BuyerListCard.fxml
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/MeetUpListCard.fxml
  src/main/resources/view/PropertyListCard.fxml
Labels: type.Enhancement, priority.Low

#162 Add Ui for Mode
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/resources/view/MainWindow.fxml
Labels: type.Enhancement, priority.High

#158 Refactor location to address
  docs/DeveloperGuide.md
  docs/UserGuide.md
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/commands/property/AddCommand.java
  src/main/java/seedu/address/logic/commands/property/EditCommand.java
  src/main/java/seedu/address/logic/commands/property/FindCommand.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/logic/parser/property/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/property/EditCommandParser.java
  src/main/java/seedu/address/logic/parser/property/FindCommandParser.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/property/Address.java
  src/main/java/seedu/address/model/property/AddressContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/property/Property.java
  src/main/java/seedu/address/model/util/SamplePropertyDataUtil.java
  src/main/java/seedu/address/storage/property/JsonAdaptedProperty.java
  src/main/java/seedu/address/ui/meetup/MeetUpCard.java
  src/main/java/seedu/address/ui/meetup/MeetUpListPanel.java
  src/main/java/seedu/address/ui/property/PropertyCard.java
  src/main/resources/view/PropertyListCard.fxml
  src/test/data/JsonPropertyListStorageTest/invalidAndValidPropertyList.json
  src/test/data/JsonPropertyListStorageTest/invalidPropertyList.json
  src/test/data/JsonSerializablePropertyListTest/duplicatePropertyList.json
  src/test/data/JsonSerializablePropertyListTest/invalidPropertyList.json
  src/test/data/JsonSerializablePropertyListTest/typicalPropertyList.json
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/buyer/AddCommandTest.java
  src/test/java/seedu/address/model/property/AddressTest.java
  src/test/java/seedu/address/model/property/LocationTest.java
  src/test/java/seedu/address/model/property/PropertyTest.java
  src/test/java/seedu/address/storage/property/JsonAdaptedPropertyTest.java
  src/test/java/seedu/address/testutil/property/PropertyBuilder.java
  src/test/java/seedu/address/testutil/property/TypicalProperties.java
Labels: type.Enhancement, priority.Low

#170 Test add property
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/property/AddCommandIntegrationTest.java
  src/test/java/seedu/address/logic/commands/property/AddCommandTest.java
  src/test/java/seedu/address/logic/parser/property/AddCommandParserTest.java
  src/test/java/seedu/address/storage/property/JsonPropertyListStorageTest.java
  src/test/java/seedu/address/testutil/property/TypicalProperties.java
Labels: type.Task, priority.High

#172 Update model class diagram
  docs/diagrams/ModelClassDiagram.puml
Labels: type.Task, priority.High

#175 Add Property EditCommand test
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/commands/meetup/EditCommand.java
  src/main/java/seedu/address/logic/commands/property/DeleteCommand.java
  src/main/java/seedu/address/logic/commands/property/EditCommand.java
  src/main/java/seedu/address/logic/parser/BuyerListParser.java
  src/main/java/seedu/address/logic/parser/property/EditCommandParser.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/property/EditCommandTest.java
  src/test/java/seedu/address/logic/commands/property/ViewCommandTest.java
  src/test/java/seedu/address/logic/parser/BuyerListParserTest.java
  src/test/java/seedu/address/logic/parser/property/EditCommandParserTest.java
  src/test/java/seedu/address/logic/parser/property/PropertyCommandParserTest.java
  src/test/java/seedu/address/testutil/property/PropertyUtil.java
Labels: type.Task, priority.Medium

#168 Parser error handling
  src/main/java/seedu/address/logic/commands/SwitchParserModeCommand.java
  src/main/java/seedu/address/logic/parser/AbcliParser.java
  src/main/java/seedu/address/logic/parser/SwitchParserModeCommandParser.java
  src/main/java/seedu/address/logic/parser/exceptions/InvalidParserModeException.java
Labels: type.Task, priority.Medium

#180 Add storage manager tests
  src/main/java/seedu/address/MainApp.java
  src/main/java/seedu/address/model/MeetUpList.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/PropertyList.java
  src/main/java/seedu/address/storage/buyer/JsonBuyerListStorage.java
  src/main/java/seedu/address/storage/meetup/JsonMeetUpListStorage.java
  src/main/java/seedu/address/storage/property/JsonPropertyListStorage.java
  src/test/java/seedu/address/storage/StorageManagerTest.java
Labels: type.Enhancement, priority.High

#178 Add test cases for string methods in From and To in MeetUp
  src/test/java/seedu/address/model/meetup/FromTest.java
  src/test/java/seedu/address/model/meetup/ToTest.java
Labels: type.Task, priority.Medium

#173 Property delete command test cases
  src/main/java/seedu/address/logic/commands/property/DeleteCommand.java
  src/test/java/seedu/address/logic/commands/property/DeleteCommandTest.java
  src/test/java/seedu/address/logic/parser/property/DeleteCommandParserTest.java
Labels: type.Task, priority.Medium

#174 Test property model
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/commands/property/EditCommand.java
  src/main/java/seedu/address/model/property/Property.java
  src/main/java/seedu/address/model/property/UniquePropertyList.java
  src/main/java/seedu/address/storage/property/JsonAdaptedProperty.java
  src/main/java/seedu/address/ui/property/PropertyCard.java
  src/test/data/JsonSerializablePropertyListTest/typicalPropertyList.json
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/model/PropertyListTest.java
  src/test/java/seedu/address/model/property/PropertyTest.java
  src/test/java/seedu/address/model/property/UniquePropertyListTest.java
  src/test/java/seedu/address/storage/property/JsonAdaptedPropertyTest.java
  src/test/java/seedu/address/testutil/property/EditPropertyDescriptorBuilder.java
  src/test/java/seedu/address/testutil/property/PropertyBuilder.java
  src/test/java/seedu/address/testutil/property/PropertyUtil.java
  src/test/java/seedu/address/testutil/property/TypicalProperties.java
Labels: type.Task, priority.High
